# Generated by Django 5.2.15 on 2026-06-07 05:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbulanceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital_name', models.CharField(db_index=True, max_length=255)),
                ('service_type', models.CharField(choices=[('government', 'Government'), ('private', 'Private'), ('ngo', 'NGO/Charitable')], db_index=True, default='government', max_length=15)),
                ('contact_number', models.CharField(max_length=32, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (Nepal format preferred).', regex='^\\+?9779\\d{8}$|^\\+?977-?\\d{7,10}$|^\\d{7,15}$')])),
                ('contact_alt', models.CharField(blank=True, max_length=32, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (Nepal format preferred).', regex='^\\+?9779\\d{8}$|^\\+?977-?\\d{7,10}$|^\\d{7,15}$')])),
                ('address', models.CharField(max_length=500)),
                ('district', models.CharField(blank=True, db_index=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_24h', models.BooleanField(default=True)),
                ('has_icu', models.BooleanField(default=False)),
                ('has_oxygen', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['hospital_name'],
            },
        ),
        migrations.CreateModel(
            name='BloodBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('district', models.CharField(blank=True, db_index=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=32, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (Nepal format preferred).', regex='^\\+?9779\\d{8}$|^\\+?977-?\\d{7,10}$|^\\d{7,15}$')])),
                ('phone_alt', models.CharField(blank=True, max_length=32, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (Nepal format preferred).', regex='^\\+?9779\\d{8}$|^\\+?977-?\\d{7,10}$|^\\d{7,15}$')])),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_24h', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MedicineCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Material icon name', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'medicine categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MedicalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('height_cm', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(250)])),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)])),
                ('allergies', models.TextField(blank=True)),
                ('chronic_conditions', models.TextField(blank=True)),
                ('current_medications', models.TextField(blank=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=32, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (Nepal format preferred).', regex='^\\+?9779\\d{8}$|^\\+?977-?\\d{7,10}$|^\\d{7,15}$')])),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=50)),
                ('share_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medical Profile',
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('generic_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('brand_name', models.CharField(blank=True, max_length=255)),
                ('dosage_form', models.CharField(blank=True, help_text='e.g. tablet, syrup, injection, inhaler', max_length=50)),
                ('strength', models.CharField(blank=True, help_text='e.g. 500mg, 5mg/ml', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_essential', models.BooleanField(db_index=True, default=False)),
                ('requires_prescription', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicines', to='core.medicinecategory')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('generic_name', 'strength', 'dosage_form')},
            },
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('address', models.CharField(max_length=500)),
                ('district', models.CharField(blank=True, db_index=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=32, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (Nepal format preferred).', regex='^\\+?9779\\d{8}$|^\\+?977-?\\d{7,10}$|^\\d{7,15}$')])),
                ('phone_alt', models.CharField(blank=True, max_length=32, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (Nepal format preferred).', regex='^\\+?9779\\d{8}$|^\\+?977-?\\d{7,10}$|^\\d{7,15}$')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_24h', models.BooleanField(default=False)),
                ('opens_at', models.TimeField(blank=True, null=True)),
                ('closes_at', models.TimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('suspended', 'Suspended')], db_index=True, default='pending', max_length=20)),
                ('managed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_pharmacies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'pharmacies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PharmacyMedicineStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('availability', models.CharField(choices=[('available', 'Available'), ('low_stock', 'Low Stock'), ('out_of_stock', 'Out of Stock')], db_index=True, default='available', max_length=20)),
                ('price_npr', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity_on_hand', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('last_verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='core.medicine')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='core.pharmacy')),
            ],
            options={
                'ordering': ['medicine__name'],
            },
        ),
        migrations.CreateModel(
            name='BloodStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], db_index=True, max_length=3)),
                ('stock_level', models.CharField(choices=[('adequate', 'Adequate'), ('low', 'Low'), ('critical', 'Critical'), ('unavailable', 'Unavailable')], db_index=True, default='adequate', max_length=15)),
                ('units_available', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('blood_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_stocks', to='core.bloodbank')),
            ],
            options={
                'ordering': ['blood_group'],
                'unique_together': {('blood_bank', 'blood_group')},
            },
        ),
        migrations.AddIndex(
            model_name='pharmacy',
            index=models.Index(fields=['district', 'is_active'], name='core_pharma_distric_0a795d_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacymedicinestock',
            index=models.Index(fields=['availability', 'pharmacy'], name='core_pharma_availab_874043_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pharmacymedicinestock',
            unique_together={('pharmacy', 'medicine')},
        ),
    ]
